In [1]:
import numpy as np

Scenario 1

In [2]:
a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [3]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

Scenario 2

In [4]:
a3=np.arange(9).reshape(3,3)
a4=np.arange(3).reshape(1,3)
print(a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [5]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

Rules for broadcasting

In [6]:
# if x=m and y=n, operation will take place
a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [10]:
# if x=1 and y=n then also operation will take place(some dimension)

a5=np.arange(3).reshape(1,3)
a6=np.arange(12).reshape(4,3)

print(a5)
print(a6)

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
a5+a6

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [11]:
# if x=1 and y!=n then also operation will not take place

a9=np.arange(3).reshape(1,3)
a10=np.arange(16).reshape(4,4)

print(a9)
print(a10)

[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [12]:
a9 + a10

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [13]:
# if x=1 and n=1 then y==m, operation to take place

a11=np.arange(3).reshape(1,3)
a12=np.arange(3).reshape(3,1)
print(a11)
print(a12)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [14]:
a11 + a12

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [16]:
# if x=1 and y=1 then the operation will take place no matter what 

a13=np.arange(1).reshape(1,1)
a14=np.arange(20).reshape(4,5)

print(a13)
print(a14)

[[0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
a13 + a14

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
# if they are from different dimensions

a15=np.arange(4)
a16=np.arange(20).reshape(5,4)

print(a15)
print(a16)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [19]:
a15 + a16

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])