In [1]:
import numpy as np

Random module

In [3]:
np.random.random()

0.8838893826045724

In [7]:
# seed function give same random value again and again
np.random.seed(1)
np.random.random()

0.417022004702574

In [10]:
# when we want to generate random value in given range we use another function known as uniform()

np.random.uniform(1,12)

1.0012581229907938

In [12]:
np.random.uniform(1,100,10).reshape(2,5)

array([[87.9336262 ,  3.71137173, 67.37628351, 42.31317543, 56.31029302],
       [14.89830692, 20.61204742, 80.2737123 , 96.857896  , 32.02899364]])

In [19]:
# it give a random integer in given range
np.random.randint(1,10,15).reshape(3,5)

array([[9, 8, 4, 7, 6],
       [2, 4, 5, 9, 2],
       [5, 1, 4, 3, 1]], dtype=int32)

In [23]:
arr1=np.random.randint(1,10,6)
arr1

array([7, 9, 1, 3, 8, 8], dtype=int32)

In [24]:
np.max(arr1)

np.int32(9)

In [25]:
np.min(arr1)

np.int32(1)

In [28]:
# to find the index of the max and min numbers of the array
np.argmax(arr1)

np.int64(1)

In [29]:
np.argmin(arr1)

np.int64(2)

In [32]:
arr2=np.random.randint(1,10,6)
arr2

array([5, 6, 7, 3, 6, 8], dtype=int32)

In [33]:
arr2[arr2%2==1]=-1
arr2

array([-1,  6, -1, -1,  6,  8], dtype=int32)

In [35]:
# where(condition,True,False)

arr3=np.random.randint(1,50,6)
arr3

array([49, 19, 33, 14, 11, 24], dtype=int32)

In [38]:
out=np.where(arr3%2==1,-1,arr3)
out

array([-1, -1, -1, 14, -1, 24], dtype=int32)

In [37]:
arr3

array([49, 19, 33, 14, 11, 24], dtype=int32)

In [39]:
arr4=np.random.randint(1,50,10)
arr4

array([18,  8, 25, 11, 29, 21, 33, 13,  2, 31], dtype=int32)

In [43]:
a=np.sort(arr4)
a

array([ 2,  8, 11, 13, 18, 21, 25, 29, 31, 33], dtype=int32)

In [46]:
np.percentile(a,25)

np.float64(11.5)

In [47]:
np.percentile(a,50)

np.float64(19.5)

In [48]:
np.percentile(a,100)

np.float64(33.0)